### ISSUE TITLE
implement fusion auth

### ISSUE THREAD

**Issue by tsearle** [openline-ai/openline-voice-kamailio-server#3]
kamailio must have authentication before it can go into production

the webrtc must be able to consume the jwt token generated by fusion auth in the agent app

**Comment by edifirut** [comment]
Let's have a chat before implementing this. We might ditch fusion-auth

**Comment by tsearle** [comment]
I though it would remain for agent app as we are identifying actual users.

I prefer to implement the JWT auth with the current frame work, and hit whatever new jwt server later when it comes to exist

This is blocking me from being able to deploy kamailio in production

**Comment by tsearle** [comment]
after discussion with @edifirut and @xvasi it has been decided to stick with fusion auth (for now)

this will be revisited probably later this quarter when a new auth system has been developed

**Comment by tsearle** [comment]
I was unable to get CORS working for sending the JWT token

the new strategy is to
1. have the AgentAPI generate an ephemeral auth token using a shared secret  between it and kamailio
2. use this credentials for SIP digest authentication in kamailio
